{
  "hash": "88a26d2855071d1807a5f3e15b5c9902",
  "result": {
    "engine": "knitr",
    "markdown": "# Extra: CA2 {#sec-extraCA2 .unnumbered}\n\n::: callout-note\n<a href=\"downloads/CA2_extra_R_student.qmd\" download=\"CA2_extra_R_student.qmd\">\n  <i class=\"bi bi-download\"></i> Download file\n</a> \n\n:::\n\n## Overview {.unnumbered}\n\nCoverage: L10-L20, P4-P6\n\nThis is a document to **supplement** the document for CA1. Keep in mind that CA2 covers **all** lectures and practicals. Please work through `CA1_extra_R.qmd` again as well.\n\nNote that there are often many possible paths to the correct solution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse); theme_set(theme_classic())\nlibrary(readxl)\nlibrary(cowplot)\nset.seed(2026)\n```\n:::\n\n\n\n## Air quality\n\nThe `airquality` dataset is available in R upon start-up, and gives daily values of mean ozone, solar radiation, mean wind speed, and max temperature at LaGuardia Airport in New York City (`?airquality`).\n\nAssume we do not know the population parameters, but wish to estimate the probability of observing our sample mean under the hypothesis that $\\mu = 11 mph$. What is the T statistic?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nT_mu11 <- (mean(airquality$Wind) - 11)/(sd(airquality$Wind)/sqrt(nrow(airquality)))\nT_mu11\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -3.660178\n```\n\n\n:::\n:::\n\n:::\n\n:::\n\nUnder this hypothesized $\\mu$, what is the probability of collecting a sample with a mean further from $\\mu$ than in this dataset?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\n2 * pt(T_mu11, nrow(airquality)-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0003471392\n```\n\n\n:::\n:::\n\n:::\n\n:::\n\n## Iris\n\nThe `iris` dataset is available in R upon start-up.\n\n**Research question:** What is the difference in mean sepal area among *Iris setosa*, *I. versicolor*, and *I. virginica*?\n\nWhat type of variables are the response and predictor variables?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> Response: continuous\n\n> Predictor: categorical\n\n:::\n\n:::\n\nWhat analysis is appropriate for this question?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> ANOVA\n\n:::\n\n:::\n\nFor this question, is `Species` a fixed effect or a random effect?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> `Species` is a fixed effect.\n\n:::\n\n:::\n\n### Calculate Sepal.Area\n\nCreate a new column in the data.frame `iris` called `Sepal.Area`.\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\niris$Sepal.Area <- iris$Sepal.Length * iris$Sepal.Width\nstr(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t150 obs. of  6 variables:\n $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...\n $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...\n $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...\n $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...\n $ Species     : Factor w/ 3 levels \"setosa\",\"versicolor\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ Sepal.Area  : num  17.8 14.7 15 14.3 18 ...\n```\n\n\n:::\n:::\n\n:::\n\n:::\n\nCreate a histogram of Sepal.Area, showing the distribution for each species using the same limits for the x-axis.\n\nOption 1. ggplot:\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nlibrary(tidyverse)\n# facet_grid() by default uses the same x-axis for all panels\nggplot(iris, aes(Sepal.Area)) +\n  geom_histogram(binwidth=2) + \n  facet_grid(Species~.)\n```\n\n::: {.cell-output-display}\n![](CA2_extra_R_KEY_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n:::\n\nOption 2. Base R:\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(3,1)) \n# Need to set xlim for each panel in base R\nx_lims <- range(iris$Sepal.Area)\nhist(iris$Sepal.Area[iris$Species==\"setosa\"], \n     main=\"Iris setosa\", xlab=\"Sepal Area\", xlim=x_lims)\nhist(iris$Sepal.Area[iris$Species==\"versicolor\"], \n     main=\"Iris versicolor\", xlab=\"Sepal Area\", xlim=x_lims)\nhist(iris$Sepal.Area[iris$Species==\"virginica\"], \n     main=\"Iris virginica\", xlab=\"Sepal Area\", xlim=x_lims)\n```\n\n::: {.cell-output-display}\n![](CA2_extra_R_KEY_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n:::\n\n### Perform the analysis\n\nPerform the analysis and assess the assumptions.\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nSepalArea_aov <- aov(Sepal.Area ~ Species, data=iris) \n```\n:::\n\n:::\n\n:::\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(2, 2)) \nplot(SepalArea_aov)\n```\n\n::: {.cell-output-display}\n![](CA2_extra_R_KEY_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n:::\n\nWhat assumptions of this ANOVA can you evaluate with these plots? Do they appear reasonable?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> 1.  Residual error is normally distributed.\n\n> 2.  Standard deviation of residual error is identical across groups (= homoscedastic).\n\n> Yes, both assumptions are reasonable, though there are several individuals of *Iris virginica* that are rather large. This is not so extreme as to require a transformation.\n\n:::\n\n:::\n\nWhat is the null hypothesis?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> The population means for all species are the same. That is, the populations follow identical normal distributions.\n\n:::\n\n:::\n\nWhat is the probability of the observed difference in group means if the null hypothesis were true?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(SepalArea_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value   Pr(>F)    \nSpecies       2  273.3   136.7   14.24 2.22e-06 ***\nResiduals   147 1410.7     9.6                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n> 2.22 x 10\\^-6 = 0.00000222\n\n:::\n\n:::\n\n### Follow up analysis\n\nWhat are the means and 95% confidence intervals for each species?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nlibrary(emmeans) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nemmeans(SepalArea_aov, \"Species\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Species    emmean    SE  df lower.CL upper.CL\n setosa       17.3 0.438 147     16.4     18.1\n versicolor   16.5 0.438 147     15.7     17.4\n virginica    19.7 0.438 147     18.8     20.6\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n:::\n\n:::\n\nWhat is the best interpretation of these 95% confidence intervals?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> The population mean (mu) is captured by 95% CIs in 95% of random samples of the population. The population mean is a fixed value, so the 95% CIs from this specific sample either capture mu or they do not, and we do not know which.\n\n:::\n\n:::\n\nWhat are the effect sizes and 95% confidence intervals? That is, which species are meaningfully different from one another and how confident are we in those differences?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nTukeyHSD(SepalArea_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = Sepal.Area ~ Species, data = iris)\n\n$Species\n                        diff        lwr       upr     p adj\nversicolor-setosa    -0.7316 -2.1985315 0.7353315 0.4664726\nvirginica-setosa      2.4268  0.9598685 3.8937315 0.0004006\nvirginica-versicolor  3.1584  1.6914685 4.6253315 0.0000031\n```\n\n\n:::\n:::\n\n\n> *I. virginica* is 2.43 greater than *I. setosa* (95% CI: 0.960 - 3.89; p \\< 0.001).\n\n> *I. virginica* is 3.16 greater than *I. versicolor* (95% CI: 1.69 - 4.63; p \\< 0.001).\n\n> There is no support for a difference between *I. versicolor* and *I. setosa* (p = 0.466).\n\n:::\n\n:::\n\n## Iris (reprise)\n\n**Research question:** For the species *I. virginica*, what is the effect of sepal width on petal width?\n\nWhat type of variables are the response and predictor variables?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> Response: continuous\n\n> Predictor: continuous\n\n:::\n\n:::\n\nWhat analysis is appropriate for this question?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> Linear regression\n\n:::\n\n:::\n\n### Create the appropriate data.frame\n\nCreate a new dataframe containing all columns in `iris`, but only rows where the species is `virginica`.\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nvirginica_df <- iris[iris$Species==\"virginica\",]\n```\n:::\n\n:::\n\n:::\n\nCreate a scatterplot of the relationship, with the predictor variable on the x-axis and the response variable on the y-axis.\n\nOption 1. ggplot:\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nggplot(virginica_df, aes(Sepal.Width, Petal.Width)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](CA2_extra_R_KEY_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n:::\n\nOption 2. Base R:\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(1,1))\nplot(Petal.Width ~ Sepal.Width, data=virginica_df)\n```\n\n::: {.cell-output-display}\n![](CA2_extra_R_KEY_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n:::\n\n### Perform the analysis\n\nPerform the analysis and check the assumptions.\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nwidth_lm <- lm(Petal.Width ~ Sepal.Width, data=virginica_df)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(2,2))\nplot(width_lm)\n```\n\n::: {.cell-output-display}\n![](CA2_extra_R_KEY_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n:::\n\nWhat assumptions of this linear regression can you evaluate with these plots? Do they appear reasonable?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> 1.  Residual error is normally distributed.\n\n> 2.  Standard deviation of residual error is constant across values of the predictor (= homoscedastic).\n\n> Yes, both assumptions are reasonable, though there's a hint of a possible increase in standard deviation at high fitted values (3rd plot, sqrt(abs(standardized residuals))). However, there are only two observations at the far end, so that is very plausibly due to random chance.\n\n:::\n\n:::\n\nWhat is the null hypothesis?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> There is no effect of sepal width on petal width in the population.\n\n:::\n\n:::\n\nWhat would the null hypothesis look like on the scatter plot above?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n> A flat line (slope = 0) with intercept at the mean petal width.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(1,1))\nplot(Petal.Width ~ Sepal.Width, data=virginica_df)\nabline(h=mean(virginica_df$Petal.Width))\n```\n\n::: {.cell-output-display}\n![](CA2_extra_R_KEY_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n:::\n\nWhat is the probability of the observed change in petal width per unit increase in sepal width if the null hypothesis were true?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(width_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Petal.Width ~ Sepal.Width, data = virginica_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.45473 -0.18697  0.00789  0.17050  0.45368 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   0.6641     0.3100   2.142   0.0373 *  \nSepal.Width   0.4579     0.1036   4.419 5.65e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.234 on 48 degrees of freedom\nMultiple R-squared:  0.2892,\tAdjusted R-squared:  0.2743 \nF-statistic: 19.52 on 1 and 48 DF,  p-value: 5.648e-05\n```\n\n\n:::\n:::\n\n\n> 5.65 x 10\\^-5 = 0.0000565\n\n:::\n\n:::\n\n### Follow up analysis\n\nTo three significant figures, what is the best estimate of the change in petal width per unit increase in sepal width, and what are the 95% confidence intervals?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\n# Best estimate of slope:\nsignif(coef(width_lm)[2], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSepal.Width \n      0.458 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\n# 95% CIs:\nsignif(confint(width_lm)[2,], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5 % 97.5 % \n 0.250  0.666 \n```\n\n\n:::\n:::\n\n:::\n\n:::\n\nCreate a scatter plot of the relationship and add the best fit line from the linear regression with 95% confidence intervals.\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\n# Create a sequence of Sepal.Width values to generate predictions for\nsepW_seq <- seq(min(virginica_df$Sepal.Width)*0.8, \n                max(virginica_df$Sepal.Width)*1.2, \n                length.out=100)\n# Generate predictions (fit & 95% CIs)\nwidth_preds <- predict(width_lm, interval=\"confidence\", level=0.95, \n                       newdata=data.frame(Sepal.Width=sepW_seq))\n# Plot\npar(mfrow=c(1,1))\nplot(Petal.Width ~ Sepal.Width, data=virginica_df)\nlines(sepW_seq, width_preds[, \"fit\"])\nlines(sepW_seq, width_preds[, \"lwr\"], lty=2)\nlines(sepW_seq, width_preds[, \"upr\"], lty=2)\n```\n\n::: {.cell-output-display}\n![](CA2_extra_R_KEY_files/figure-pdf/unnamed-chunk-20-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n:::\n\n## NMDS, PCA\n\nYou will not be asked to produce any R code relating to Practical 6, so I am not including extra R practice here. You should nevertheless be familiar with the concepts, confident in the steps involved, and comfortable interpreting the output.\n",
    "supporting": [
      "CA2_extra_R_KEY_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}