project:
  output-dir: _pub

book:
  title: "H2 Data Science Practicals"
  chapters:
    - index.qmd
    - P0_R_setup.qmd
    - P1_R_recap.qmd
    - P2_binomial_poisson.qmd
    - P3_normal.qmd
    - P4_t_CIs.qmd
    - P5_ANOVA_regression.qmd
    - P6_machine_learning.qmd
    - P7_appendix.qmd
  site-url: https://sz-tim.quarto.pub/h2ds-practicals
  downloads: [pdf, epub]

format:
  html:
    theme: flatly
    dark: darkly
    
  pdf:
    documentclass: book
    papersize: A4
    cover-image: figs/cover.png
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    geometry:
      - top=20mm
      - right=20mm
      - bottom=20mm
      - left=20mm
      - heightrounded
    
  epub:
    cover-image: figs/cover.png

