project:
  type: book

book:
  title: "H2SMS Practicals"
  date: "2026-09-07"
  repo-actions: [issue]
  repo-url: https://github.com/Sz-Tim/H2SMS_Practicals
  favicon: figs/one_distribution.png
  search: true

format:
  html:
    fontsize: 11pt
    code-fold: false
    code-block-bg: true
    code-summary: "Code (bonus)"
    code-link: true
    callout-appearance: simple
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/\.sz-tim\.quarto\.pub/custom


callout-appearance: simple

editor: source

custom-numbered-blocks:
  classes:
    Q.: 
      boxstyle: foldbox.simple
      collapse: false
      colors: [69B7CE, 3F6F76]

filters:
- custom-numbered-blocks

execute:
  freeze: auto

profile:
  group:
    - [man, key]