project:
  output-dir: _key

book:
  title: "H2 Data Science Practicals KEY"
  chapters:
    - index.qmd
    - P0_R_setup.qmd
    - P1_R_recap.qmd
    - probSets_P1.qmd
    - P7_appendix.qmd
  site-url: https://sz-tim.quarto.pub/h2ds-practicals-key

format:
  html:
    theme: pulse
    dark: slate

