project:
  type: book
  output-dir: _key

book:
  title: "H2 Data Science Practicals KEY"
  author: "Tim Szewczyk (v1: Tom Wilding)"
  date: today
  chapters:
    - index.qmd
    - P0_R_setup.qmd
    - P1_R_recap.qmd
    - P7_appendix.qmd
  site-url: https://sz-tim.quarto.pub/h2ds-practicals-key
  repo-actions: [issue]
  repo-url: https://github.com/Sz-Tim/H2DS_Practicals
  favicon: figs/one_distribution.png
  search: true

format:
  html:
    theme: pulse
    dark: slate
    code-fold: false
    code-block-bg: true
    code-summary: "Code (bonus)"
    code-link: true
    callout-appearance: simple
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/\.sz-tim\.quarto\.pub/custom
    sidebar:
      style: "docked"
      search: true
      collapse-level: 3

callout-appearance: simple

editor: source

custom-numbered-blocks:
  classes:
    Q.: 
      boxstyle: foldbox.simple
      collapse: false
      colors: [69B7CE, 3F6F76]

filters:
- custom-numbered-blocks

execute:
  freeze: auto
