{
  "hash": "544e6d8ab3f32923667e8d74b57fc986",
  "result": {
    "engine": "knitr",
    "markdown": "# Problem Set 5 {#sec-P5_probSet .unnumbered}\n\n::: callout-note\n\n<a href=\"downloads/probSets_P5_student.qmd\" download=\"probSets_P5_student.qmd\">\n  <i class=\"bi bi-download\"></i>  Download file\n</a> \n\nPlease render this file to .html and submit via Brightspace.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse); theme_set(theme_classic())\nlibrary(readxl)\nlibrary(emmeans)\nset.seed(2026)\n```\n:::\n\n\n## T-tests, ANOVA, and regression\n\nFor each scenario, select an appropriate analysis given the dataset. Follow the workflow illustrated in the practical and in the lectures, checking assumptions and applying transformations as needed.\n\n### Scenario 1\n\n\n**Research question:** Do critical thermal limits change with repeated heatwave exposure in kelp?\n\nIn an experiment similar to [King et al. 2024](https://doi.org/10.1111/1365-2435.14622), a (hypothetical) H4 student measured critical thermal maxima (CT~max~) on the kelp species *Laminaria hyperborea* under 1) no previous heat exposure, 2) recent moderate heat exposure, and 3) recent extreme heat exposure. \n\nIdentify the response and predictor variables, as well as what type of variable each is. \n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\nCT~max~ is the response; it is continuous.\n\nHeat exposure is the predictor; it is categorical.\n\n:::\n:::\n\nNext, load the data from the \"MHW\" sheet in \"H2SMS_practicalData.xlsx\" and perform appropriate checks.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nmhw_df <- read_xlsx(\"data/H2SMS_practicalData.xlsx\", sheet=\"MHW\")\nstr(mhw_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [90 x 3] (S3: tbl_df/tbl/data.frame)\n $ ind_id   : num [1:90] 1 1 1 2 2 2 3 3 3 4 ...\n $ treatment: chr [1:90] \"Control\" \"Moderate\" \"Extreme\" \"Control\" ...\n $ CTmax    : num [1:90] 29.4 29.2 24.1 30.5 29.1 24 30.3 29.2 24 30 ...\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(mhw_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     ind_id      treatment             CTmax      \n Min.   : 1.0   Length:90          Min.   :23.50  \n 1st Qu.: 8.0   Class :character   1st Qu.:24.20  \n Median :15.5   Mode  :character   Median :29.00  \n Mean   :15.5                      Mean   :27.68  \n 3rd Qu.:23.0                      3rd Qu.:29.88  \n Max.   :30.0                      Max.   :30.50  \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nmhw_df$treatment <- factor(mhw_df$treatment, levels=c(\"Control\", \"Moderate\", \"Extreme\"))\n```\n:::\n\n\n:::\n:::\n\nWhich analysis is most appropriate?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\nANOVA\n\n:::\n:::\n\n\nWhat is the null hypothesis?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n$\\mu_{Control} = \\mu_{Moderate} = \\mu_{Extreme}$\n\n:::\n:::\n\n\nPerform the analysis, including assumption checks. Calculate appropriate confidence intervals, make appropriate comparisons, and summarise results concisely in one short paragraph including key statistics.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nmhw_aov <- aov(CTmax ~ treatment, data=mhw_df)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(2,2))\nplot(mhw_aov)\n```\n\n::: {.cell-output-display}\n![](probSets_P5_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(1,1))\n```\n:::\n\n\nAssumptions look reasonable. Approximately normally distributed residuals and similar residual variance in each treatment.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(mhw_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)    \ntreatment    2  631.3  315.66    5502 <2e-16 ***\nResiduals   87    5.0    0.06                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThere is a significant effect of treatment (p < 0.05).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nem_df <- emmeans(mhw_aov, specs=\"treatment\")\nem_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n treatment emmean     SE df lower.CL upper.CL\n Control    30.05 0.0437 87    29.96    30.14\n Moderate   29.02 0.0437 87    28.93    29.10\n Extreme    23.99 0.0437 87    23.90    24.07\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nTukeyHSD(mhw_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = CTmax ~ treatment, data = mhw_df)\n\n$treatment\n                      diff       lwr        upr p adj\nModerate-Control -1.033333 -1.180801 -0.8858657     0\nExtreme-Control  -6.063333 -6.210801 -5.9158657     0\nExtreme-Moderate -5.030000 -5.177468 -4.8825324     0\n```\n\n\n:::\n:::\n\n\n> There was a significant difference in CT~max~ among all treatments (F~2,87~=5502, p < 0.001). The individuals in the control showed the most heat tolerance (mean CT~max~ [95% CI]: 30.1 C [30.0-30.14 C]), with a slight decline in individuals previously exposed to moderate heatwave conditions (29.0 C [28.9-29.1 C]) and a dramatic decrease in heat tolerance for individuals previously exposed to extreme heatwave conditions (24.0 C [23.9-24.1 C]). \n\n::: callout-note\nDepending on the specific question and focus, you might focus on the mean densities (listing them specifically in text) or on the differences: use the text to emphasize the main results of interest. Further detail can be included in figures and tables.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nggplot(mhw_df, aes(treatment)) +\n  geom_point(aes(y=CTmax), alpha=0.5) +\n  geom_point(data=as_tibble(em_df), aes(y=emmean), shape=1, size=3) +\n  geom_errorbar(data=as_tibble(em_df), aes(ymin=lower.CL, ymax=upper.CL), width=0.25) + \n  labs(x=\"Treatment\", \n       y=\"CTmax (C)\")\n```\n\n::: {.cell-output-display}\n![CT~max~ in *Laminaria hyperborea* under different prior heatwave exposures. Observed values (small points) along with mean (open points) and 95% confidence intervals.](probSets_P5_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n:::\n:::\n\n\n\n\n### Scenario 2\n\n**Research question:** Is the average concentration of *Alexandrium spp* in an area greater than 40 cells per litre?\n\nIn the UK, shellfish cannot be harvested on aquaculture farms if densities of harmful algal species exceed certain levels. For example, *Alexandrium spp* release paralytic shellfish toxins, and growers are not allowed to harvest when *Alexandrium spp* exceeds 40 cells per litre. \n\nI've collected 13 water samples and enumerated the number of *Alexandrium spp* cells. \n\n::: callout-note\nNB: This is *not* quite how the regulatory monitoring works!\n:::\n\nIdentify the response and predictor variables, as well as what type of variable each is. \n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\nAlexandrium density is the response; it is continuous.\n\nThere is not a predictor variable.\n\n:::\n:::\n\nNext, load the data from the \"Alexandrium\" sheet in \"H2SMS_practicalData.xlsx\" and perform appropriate checks.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nalex_df <- read_xlsx(\"data/H2SMS_practicalData.xlsx\", sheet=\"Alexandrium\")\nstr(alex_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [13 x 2] (S3: tbl_df/tbl/data.frame)\n $ sample_id   : num [1:13] 1 2 3 4 5 6 7 8 9 10 ...\n $ alex_cells_L: num [1:13] 29.2 31.8 29.6 25.6 32 33.8 31.5 31.5 30.6 33.4 ...\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(alex_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   sample_id   alex_cells_L  \n Min.   : 1   Min.   :24.90  \n 1st Qu.: 4   1st Qu.:29.20  \n Median : 7   Median :31.50  \n Mean   : 7   Mean   :30.38  \n 3rd Qu.:10   3rd Qu.:32.00  \n Max.   :13   Max.   :34.60  \n```\n\n\n:::\n:::\n\n\n:::\n:::\n\nWhich analysis is most appropriate?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\nOne-sample t-test\n\n:::\n:::\n\nWhat is the null hypothesis?\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n$\\mu_{Alex} \\leq 40$\n\n:::\n:::\n\nPerform the analysis, including assumption checks. Calculate appropriate confidence intervals, make appropriate comparisons, and summarise results concisely in one short paragraph including key statistics.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(1,2))\nhist(alex_df$alex_cells_L, breaks=5)\nqqnorm(alex_df$alex_cells_L); qqline(alex_df$alex_cells_L)\n```\n\n::: {.cell-output-display}\n![](probSets_P5_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nData are reasonably normal.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nt.test(alex_df$alex_cells_L, mu=40, alternative=\"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  alex_df$alex_cells_L\nt = -11.134, df = 12, p-value = 1\nalternative hypothesis: true mean is greater than 40\n95 percent confidence interval:\n 28.83643      Inf\nsample estimates:\nmean of x \n 30.37692 \n```\n\n\n:::\n:::\n\n\n> We did not find evidence that the mean density of *Alexandrium* cells was above 40 cells L^-1^ (t~12~=-11.1, p = 1), with an observed mean density of 30.4 (one-tailed 95% confidence limit: 28.8).\n\n:::\n:::\n\n\n### Scenario 3\n\n\n**Research question:** Does mean seagrass shoot density differ among patches?\n\nThe data consists of seagrass shoot density measured by snorkelers in 20 randomly located quadrats in each of 3 lochs in western Scotland. \n\nIdentify the response and predictor variables, as well as what type of variable each is. \n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\nSeagrass shoot density is the response; it is continuous.\n\nLoch is the predictor; it is categorical.\n\n:::\n:::\n\nNext, load the data from the \"Seagrass\" sheet in \"H2SMS_practicalData.xlsx\" and perform appropriate checks.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nseagrass_df <- read_xlsx(\"data/H2SMS_practicalData.xlsx\", sheet=\"Seagrass\")\nstr(seagrass_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [60 x 3] (S3: tbl_df/tbl/data.frame)\n $ loch      : chr [1:60] \"Hourn\" \"Hourn\" \"Hourn\" \"Hourn\" ...\n $ quadrat_id: num [1:60] 1 2 3 4 5 6 7 8 9 10 ...\n $ obs       : num [1:60] 39.7 46.8 26.4 38.4 70.7 69.7 60.9 23.8 66.8 199 ...\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(seagrass_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     loch             quadrat_id         obs        \n Length:60          Min.   : 1.00   Min.   :  8.20  \n Class :character   1st Qu.: 5.75   1st Qu.: 26.50  \n Mode  :character   Median :10.50   Median : 39.90  \n                    Mean   :10.50   Mean   : 54.35  \n                    3rd Qu.:15.25   3rd Qu.: 61.55  \n                    Max.   :20.00   Max.   :319.30  \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nseagrass_df$loch <- factor(seagrass_df$loch)\n```\n:::\n\n\n:::\n:::\n\nWhich analysis is most appropriate?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\nANOVA\n\n:::\n:::\n\n\nWhat is the null hypothesis?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n$\\mu_{Ailort} = \\mu_{Duich} = \\mu_{Hourn}$\n\n:::\n:::\n\n\nPerform the analysis, including assumption checks. Calculate appropriate confidence intervals, make appropriate comparisons, and summarise results concisely in one short paragraph including key statistics.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nseagrass_aov <- aov(obs ~ loch, data=seagrass_df)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(2,2))\nplot(seagrass_aov)\n```\n\n::: {.cell-output-display}\n![](probSets_P5_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(1,1))\n```\n:::\n\n\nNormality is not good, and the variance seems to be different among lochs, with an apparent increase with the fitted value (i.e., variance increases with the mean). A log transform is a reasonable choice to try.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nseagrass_df$log_obs <- log(seagrass_df$obs)\nseagrass_aov <- aov(log_obs ~ loch, data=seagrass_df)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(2,2))\nplot(seagrass_aov)\n```\n\n::: {.cell-output-display}\n![](probSets_P5_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(1,1))\n```\n:::\n\n\nNot perfect, but much better and close enough.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(seagrass_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nloch         2  0.749  0.3743   0.906   0.41\nResiduals   57 23.550  0.4132               \n```\n\n\n:::\n:::\n\n\nThere is no significant effect of loch (p > 0.05).\n\n> There was no a significant difference in mean seagrass shoot density among lochs (F~2,57~=0.906, p = 0.41).  \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nem_df <- emmeans(seagrass_aov, specs=\"loch\")\nem_df <- as_tibble(em_df) |>\n  mutate(exp_mn=exp(emmean),\n         exp_lo=exp(lower.CL),\n         exp_hi=exp(upper.CL))\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nggplot(seagrass_df, aes(loch)) +\n  geom_point(aes(y=obs), alpha=0.5) +\n  geom_point(data=em_df, aes(y=exp_mn), shape=1, size=3) +\n  geom_errorbar(data=em_df, aes(ymin=exp_lo, ymax=exp_hi), width=0.25) + \n  labs(x=\"Loch\", \n       y=\"Seagrass shoot density (n/m2)\")\n```\n\n::: {.cell-output-display}\n![Seagrass shoot density. Observed values (small points) along with mean (open points) and 95% confidence intervals.](probSets_P5_files/figure-pdf/unnamed-chunk-24-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nOr, potentially consider the log-scale version:\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nggplot(seagrass_df, aes(loch)) +\n  geom_point(aes(y=obs), alpha=0.5) +\n  geom_point(data=em_df, aes(y=exp_mn), shape=1, size=3) +\n  geom_errorbar(data=em_df, aes(ymin=exp_lo, ymax=exp_hi), width=0.25) + \n  labs(x=\"Loch\", \n       y=\"Seagrass shoot density (n/m2)\") +\n  scale_y_log10() + \n   guides(y=\"axis_logticks\")\n```\n\n::: {.cell-output-display}\n![Seagrass shoot density. Observed values (small points) along with mean (open points) and 95% confidence intervals.](probSets_P5_files/figure-pdf/unnamed-chunk-25-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n:::\n:::\n\n\n\n\n### Scenario 4\n\n**Research question:** Does egg hatching success rate of *Acartia tonsa* depend on temperature?\n\nA (hypothetical) H4 student has decided to replicate one of the experiments of [Holste and Peck (2006)]( https://doi.org/10.1007/s00227-005-0132-0) to test the effect of temperature on egg hatching success of the copepod *Acartia tonsa*. Their data are in the \"HatchTemp\" sheet in \"H2SMS_practicalData.xlsx\", containing the temperature (C) and hatching success rate (%) for 3 replicates at each temperature.\n\n\n\n\n\nIdentify the response and predictor variables, as well as what type of variable each is. \n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\nHatching success rate is the response; it is continuous and constrained 0-100.\n\nTemperature is the predictor; it is continuous\n\n:::\n:::\n\nNext, load the data from the \"HatchTemp\" sheet in \"H2SMS_practicalData.xlsx\" and perform appropriate checks.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nhatchTemp_df <- read_xlsx(\"data/H2SMS_practicalData.xlsx\", sheet=\"HatchTemp\")\nstr(hatchTemp_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [33 x 3] (S3: tbl_df/tbl/data.frame)\n $ temp         : num [1:33] 8 8 8 9 9 9 10 10 10 11 ...\n $ replicate    : num [1:33] 1 2 3 1 2 3 1 2 3 1 ...\n $ hatch_percent: num [1:33] 26.6 39.7 36.2 53.1 44.6 ...\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(hatchTemp_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      temp      replicate hatch_percent  \n Min.   : 8   Min.   :1   Min.   :26.55  \n 1st Qu.:10   1st Qu.:1   1st Qu.:44.57  \n Median :13   Median :2   Median :57.32  \n Mean   :13   Mean   :2   Mean   :57.49  \n 3rd Qu.:16   3rd Qu.:3   3rd Qu.:68.90  \n Max.   :18   Max.   :3   Max.   :98.25  \n```\n\n\n:::\n:::\n\n\n:::\n:::\n\nWhich analysis is most appropriate?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\nLinear regression\n\n:::\n:::\n\n\nWhat is the null hypothesis?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n$\\beta = 0$\n\n:::\n:::\n\n\nPerform the analysis, including assumption checks. Calculate appropriate confidence intervals, make appropriate comparisons, and summarise results concisely in one short paragraph including key statistics.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nhatchTemp_lm <- lm(hatch_percent ~ temp, data=hatchTemp_df)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(2,2))\nplot(hatchTemp_lm)\n```\n\n::: {.cell-output-display}\n![](probSets_P5_files/figure-pdf/unnamed-chunk-31-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(1,1))\n```\n:::\n\n\nAssumptions look reasonable. Approximately normally distributed residuals and similar residual variance in across temperatures.\n\n::: callout-note\nNote that the response variable is a percentage. In this case, the assumptions look reasonable for the original data, but be aware that extrapolating to temperatures beyond the measured range would very quickly lead to impossible predictions! \n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(hatchTemp_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = hatch_percent ~ temp, data = hatchTemp_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-19.8833  -5.3352   0.2248   5.5588  24.0609 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.2321     7.0053   0.461    0.648    \ntemp          4.1739     0.5236   7.972 5.33e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.512 on 31 degrees of freedom\nMultiple R-squared:  0.6721,\tAdjusted R-squared:  0.6615 \nF-statistic: 63.55 on 1 and 31 DF,  p-value: 5.326e-09\n```\n\n\n:::\n:::\n\n\nThere is a significant effect of temperature (p < 0.05).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nconfint(hatchTemp_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %    97.5 %\n(Intercept) -11.055296 17.519538\ntemp          3.106048  5.241831\n```\n\n\n:::\n:::\n\n\n> Hatching success rate increased with temperature (mean [95% CI]: 4.17 [3.1-5.24] percentage points per degree C; p < 0.001, R^2^~adj~ = 0.66, n=33). \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nggplot(hatchTemp_df, aes(temp, hatch_percent)) +\n  geom_point(alpha=0.5) +\n  geom_smooth(method=\"lm\") +\n  scale_x_continuous(\"Temperature (C)\", breaks=seq(8, 18, by=2)) +\n  scale_y_continuous(\"Hatching success (%)\", limits=c(0, 100))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Hatching success rate by temperature. Observed values (small points) along with fitted line and 95% confidence interval.](probSets_P5_files/figure-pdf/unnamed-chunk-34-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "probSets_P5_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}