{
  "hash": "f9c222451bb47c5a7c2cb063bdf875b4",
  "result": {
    "engine": "knitr",
    "markdown": "# Problem Set 4 {#sec-P4_probSet .unnumbered}\n\n::: callout-note\n<a href=\"downloads/probSets_P4_student.qmd\" download=\"probSets_P4_student.qmd\"> <i class=\"bi bi-download\"></i> Download file </a>\n\nPlease render this file to .html and submit via Brightspace.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse); theme_set(theme_classic())\nlibrary(readxl)\nset.seed(2026)\n```\n:::\n\n\n## Sample mean vs. a reference value\n\n### Scenario 1\n\nA marine protected area (MPA) was established five years ago. Previous surveys from nearby fished reefs found a mean fish biomass of 12.2 kg 100m^-2^.\n\nResearchers survey 15 transects inside the MPA and want to test whether fish biomass is higher than the regional average of fished reefs.\n\nThe data are available from the \"MPA\" sheet in \"H2SMS_practicalData.xlsx\". Load and check the data.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Load and check data\"}\nMPA_df <- read_xlsx(\"data/H2SMS_practicalData.xlsx\", sheet=\"MPA\")\nstr(MPA_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [15 × 2] (S3: tbl_df/tbl/data.frame)\n $ transect        : num [1:15] 1 2 3 4 5 6 7 8 9 10 ...\n $ biomass_kg_100m2: num [1:15] 12.8 13.2 12.7 12.6 10.4 ...\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Load and check data\"}\nsummary(MPA_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    transect    biomass_kg_100m2\n Min.   : 1.0   Min.   :10.30   \n 1st Qu.: 4.5   1st Qu.:12.14   \n Median : 8.0   Median :12.79   \n Mean   : 8.0   Mean   :12.75   \n 3rd Qu.:11.5   3rd Qu.:13.46   \n Max.   :15.0   Max.   :15.02   \n```\n\n\n:::\n:::\n\n\n:::\n:::\n\nWhat is the response variable?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n> Fish biomass (kg 100m^-2^)\n\n:::\n:::\n\nWhat is the null hypothesis?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n$\\mu_{MPA} \\leq 12.2 kg \\cdot 100m^{-2}$\n\nThe mean fish biomass within the MPA is **less than or equal to** the mean fish biomass outside the MPA.\n\nNote that the hypothesis is about the *population mean*, not the *sample mean*.\n\n:::\n:::\n\nWhat is the alternative hypothesis?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n$\\mu_{MPA} > 12.2 kg \\cdot 100m^{-2}$\n\nThe mean fish biomass within the MPA is **greater than** the mean fish biomass outside the MPA.\n\nNote that the hypothesis is about the *population mean*, not the *sample mean*.\n\n:::\n:::\n\nEvaluate the null hypothesis using $\\alpha = 0.05$. Perform an appropriate analysis (including assumption checks), and report the relevant results in written text. \n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Data distribution\"}\npA <- ggplot(MPA_df, aes(biomass_kg_100m2)) + \n  geom_histogram(bins=10) + \n  geom_rug()\npB <- ggplot(MPA_df, aes(sample=biomass_kg_100m2)) + \n  geom_qq() + geom_qq_line() +\n  labs(x=\"Theoretical quantiles\", \n       y=\"Observed\")\ncowplot::plot_grid(pA, pB, nrow=1, align=\"h\", axis=\"tb\")\n```\n\n::: {.cell-output-display}\n![](probSets_P4_files/figure-html/unnamed-chunk-5-1.png){width=864}\n:::\n:::\n\n\nIt's a small sample, but the observations seem approximately normal.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Analysis\"}\nt.test(MPA_df$biomass_kg_100m2, mu=12.2, alternative=\"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  MPA_df$biomass_kg_100m2\nt = 1.5718, df = 14, p-value = 0.06916\nalternative hypothesis: true mean is greater than 12.2\n95 percent confidence interval:\n 12.13369      Inf\nsample estimates:\nmean of x \n    12.75 \n```\n\n\n:::\n:::\n\n\nIn a one-tailed one sample t-test, the mean fish biomass within the MPA (12.8 kg 100m^2^; 95% confidence limit: 12.1 kg 100m^-2^) was not significantly greater than the regional mean outside the MPA of 12.2 kg 100m^-2^ (T~14~=1.57, p=0.069).\n\n:::\n:::\n\nIn your own words, explain what the p-value represents.\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n> The p-value gives the probability of these observations if the null hypothesis were true. That is, it is the likelihood of these observed values if the MPA mean were equal to 12.2 kg 100^-2^.\n\n:::\n:::\n\n\n### Scenario 2\n\nIn New Zealand, [Brewin et al. (2000)](https://doi.org/10.1007/s002270000366) studied fecundity and spawning of the sea urchin *Evechinus chloroticus*, finding a mean annual gamete output of 0.068 g g^-1^ yr^-1^ between 1990-1994 at Dieffenbach Point. On my holiday, I decided to repeat that aspect of their experiment (securing all necessary permits and approvals). \n\nThe data are in the \"UrchinGametes\" sheet in \"H2SMS_practicalData.xlsx\", already summarised to grams of gamete per grams of urchin per year. Load the data and perform appropriate checks.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Load and check data\"}\nurchin_df <- read_xlsx(\"data/H2SMS_practicalData.xlsx\", sheet=\"UrchinGametes\")\nstr(urchin_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [20 × 2] (S3: tbl_df/tbl/data.frame)\n $ urchin_id: num [1:20] 1 2 3 4 5 6 7 8 9 10 ...\n $ output   : num [1:20] 0.0956 0.0476 0.0842 0.0775 0.06 ...\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Load and check data\"}\nsummary(urchin_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   urchin_id         output       \n Min.   : 1.00   Min.   :0.00359  \n 1st Qu.: 5.75   1st Qu.:0.05743  \n Median :10.50   Median :0.07049  \n Mean   :10.50   Mean   :0.06820  \n 3rd Qu.:15.25   3rd Qu.:0.08477  \n Max.   :20.00   Max.   :0.12041  \n```\n\n\n:::\n:::\n\n\n:::\n:::\n\nWhat is the response variable?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n> Annual gamete output (g gamete per gram of urchin per year)\n\n:::\n:::\n\nWhat is the null hypothesis?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n$\\mu_{new} = 0.068 g \\cdot g^{-1} \\cdot yr^{-1}$\n\nThe mean gamete output of the current population is **equal to** the historic mean.\n\nNote that the hypothesis is about the *population mean*, not the *sample mean*.\n\n:::\n:::\n\nWhat is the alternative hypothesis?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n$\\mu_{new} \\neq 0.068 g \\cdot g^{-1} \\cdot yr^{-1}$\n\nThe mean gamete output of the current population is **not equal to** the historic mean.\n\nNote that the hypothesis is about the *population mean*, not the *sample mean*.\n\n:::\n:::\n\nEvaluate the null hypothesis using $\\alpha = 0.05$. Perform an appropriate analysis (including assumption checks), and report the relevant results in written text. \n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Data distribution\"}\npA <- ggplot(urchin_df, aes(output)) + \n  geom_histogram(bins=10) + \n  geom_rug()\npB <- ggplot(urchin_df, aes(sample=output)) + \n  geom_qq() + geom_qq_line() +\n  labs(x=\"Theoretical quantiles\", \n       y=\"Observed\")\ncowplot::plot_grid(pA, pB, nrow=1, align=\"h\", axis=\"tb\")\n```\n\n::: {.cell-output-display}\n![](probSets_P4_files/figure-html/unnamed-chunk-10-1.png){width=864}\n:::\n:::\n\n\nThe observations seem approximately normal, given the sample size.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Analysis\"}\nt.test(urchin_df$output, mu=0.068)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  urchin_df$output\nt = 0.030502, df = 19, p-value = 0.976\nalternative hypothesis: true mean is not equal to 0.068\n95 percent confidence interval:\n 0.05467906 0.08171494\nsample estimates:\nmean of x \n 0.068197 \n```\n\n\n:::\n:::\n\n\nIn a two-tailed one sample t-test, the mean gamete output (0.0682 g g^-1^ yr^-1^; 95% CI: 0.0547-0.0817 g g^-1^ yr^-1^) was not significantly different than the historic average of 0.068 g g^-1^ yr^-1^ (T~19~=0.03, p=0.976).\n\n:::\n:::\n\nIn your own words, interpret your results with regard to the null hypothesis and the p-value.\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n> The observed gamete output was entirely plausible under the null hypothesis that the population mean was the same as in 1990-1994.\n\n:::\n:::\n\n\n\n\n## Confidence Intervals\n\nThe sheet \"Plastics\" in \"H2SMS_practicalData.xlsx\" contains observations of the number of plastic pellets per kilogram. Load the data. \n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Load and check data\"}\nplastic_df <- read_xlsx(\"data/H2SMS_practicalData.xlsx\", sheet=\"Plastics\")\nstr(plastic_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [100,000 × 2] (S3: tbl_df/tbl/data.frame)\n $ id     : num [1:100000] 1 2 3 4 5 6 7 8 9 10 ...\n $ pellets: num [1:100000] 431 673 548 560 429 498 406 591 438 406 ...\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Load and check data\"}\nsummary(plastic_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       id            pellets     \n Min.   :     1   Min.   : 66.0  \n 1st Qu.: 25001   1st Qu.:432.0  \n Median : 50001   Median :500.0  \n Mean   : 50001   Mean   :499.7  \n 3rd Qu.: 75000   3rd Qu.:567.0  \n Max.   :100000   Max.   :924.0  \n```\n\n\n:::\n:::\n\n\n:::\n:::\n\nConsider this the entire *population* of interest. \n\nWrite code to take a sample of 25 observations from this population and store it in a vector called `obs`.\n\n::: {.callout-tip collapse=TRUE}\n## Hint\n`sample()`\n:::\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nobs <- sample(plastic_df$pellets, size=25)\n```\n:::\n\n\n:::\n:::\n\nHow different is your sample mean from the true population mean?\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nmean(obs) - mean(plastic_df$pellets)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -4.3144\n```\n\n\n:::\n:::\n\n\nThe true mean is 499.7 and my sample mean was 495.4.\n\n:::\n:::\n\nWhat is the term that describes this difference?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\nSampling error: The difference between a sample statistic and the population parameter.\n\n:::\n:::\n\nCalculate 95% confidence intervals for your sample mean using only your sample. Do they include the true value?\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"The easy way\"}\nt.test(obs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  obs\nt = 20.866, df = 24, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 446.3995 544.4005\nsample estimates:\nmean of x \n    495.4 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"The hard way\"}\n# y_bar +/- T[df,95%] * SE\nmean(obs) + qt(c(0.025, 0.975), length(obs)-1) * sd(obs)/sqrt(length(obs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 446.3995 544.4005\n```\n\n\n:::\n:::\n\n\nIn this case, yes.\n:::\n:::\n\nAssuming each student starts with a different `set.seed`, what proportion of students would answer 'yes' to the previous question?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n0.95 = 95%\n\n:::\n:::\n\nIf you instead calculated 80% CIs, a) would you be more likely to capture the true mean or less? And, b) would the width of your confidence interval be larger or smaller?\n\n>\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\na) Less likely and b) smaller. An 80% CI will only include the true value in 80% of samples (under ideal conditions!), while a 95% CI will include the true value in 95% of samples. \n\n:::\n:::\n\nCalculate the 80% CI for your sample and compare.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nci_95 <- t.test(obs)$conf.int\nci_80 <- t.test(obs, conf.level=0.8)$conf.int\n\nci_95\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 446.3995 544.4005\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nci_80\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 464.1123 526.6877\nattr(,\"conf.level\")\n[1] 0.8\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nexpand_grid(confidence=c(0.8, 0.95),\n            limit=c(\"lo\", \"high\")) |>\n  mutate(limit=c(ci_80, ci_95)) |>\n  ggplot(aes(limit, confidence, group=confidence)) + \n  geom_line() +\n  geom_point(shape=\"|\") +\n  geom_vline(xintercept=mean(plastic_df$pellets), linetype=3) +\n  labs(x=\"Value\", y=\"Confidence level\")\n```\n\n::: {.cell-output-display}\n![True value (dotted line) compared to the 80% and 95% confidence interval from one sample.](probSets_P4_files/figure-html/unnamed-chunk-23-1.png){width=480}\n:::\n:::\n\n\n\n:::\n:::\n\nIf you were to run your code again (without resetting `set.seed`), what is the probability that you would collect a sample with a 90% CI that includes the true value?\n\n>\n\n::: {.content-hidden when-profile=\"man\"}\n::: callout-important\n\n90% - each (future) sample will have a 90% chance of having 90% CIs that include the true value.\n\n:::\n:::\n",
    "supporting": [
      "probSets_P4_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}