{
  "hash": "109d41baab19fdd982eb7530acd02448",
  "result": {
    "engine": "knitr",
    "markdown": "# ANOVA and regression {#sec-P5}\n\nGeneral linear models are a key member of the generalized linear modelling (GLM) family and they are among the most widely used models in the marine science literature, particularly biology. This course focuses on two subsets of linear models: ANOVA and regression. ANOVA and regression are typically used for different data modelling scenarios: ANOVA when the predictor is categorical and regression when the predictor is continuous.\n\n## Analysis of variance (ANOVA)\n\nANOVA is a method to compare means among groups and put confidence intervals on the differences between those means. For a predictor with only two categories, ANOVA is identical to the two-sample t-test, so we'll just use ANOVA.\n\n::: callout-note\nWhen you see \"analysis of variance\", think \"analysis of means\". The variance in the data is partitioned in different ways to draw conclusions about the means.\n:::\n\nIn an ANOVA, we compare the means of different groups by analyzing the variance (@fig-ANOVA_overview). The variance is partitioned into 1) the mean variance between treatment means and the overall mean (thick arrows), and 2) the mean variance within treatments (thin arrows). By comparing the magnitude of these two quantities, we draw conclusions about whether the difference between group means is plausibly due to noise or not.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(tidyverse)\ntheme_set(theme_classic())\n# simulate two populations A and B\nsigma <- 1.5\nmu_df <- data.frame(Group=c(\"A\", \"B\"),\n                    Lab=c(\"mu[A]\", \"mu[B]\"),\n                    mu=c(12, 17)) |>\n  mutate(density=dnorm(mu, mu, sigma))\n\npop_df <- data.frame(value=seq(min(mu_df$mu) - 3*sigma, \n                               max(mu_df$mu) + 3*sigma, \n                               length.out=1e3)) |>\n  mutate(A=dnorm(value, mu_df$mu[1], sigma),\n         B=dnorm(value, mu_df$mu[2], sigma)) |>\n  pivot_longer(2:3, names_to=\"Group\", values_to=\"density\")\nx_lim <- xlim(min(pop_df$value), max(pop_df$value))\ny_lim <- ylim(-max(pop_df$density)*0.1, max(pop_df$density)*1.1)\n\n# simulate sampling\nN <- 10\nset.seed(1)\nsamp_df <- data.frame(Group=rep(c(\"A\", \"B\"), each=N),\n                      y=c(rnorm(N, mu_df$mu[1], sigma),\n                          rnorm(N, mu_df$mu[2], sigma))) |>\n  mutate(ypos=seq(max(mu_df$density)*0.05, max(mu_df$density)*0.6, length.out=n())) |>\n  group_by(Group) |>\n  mutate(y_bar=mean(y),\n         y_bar_pos=mean(ypos)) |>\n  ungroup() |>\n  mutate(y_bar_lab=max(ypos)*1.1,\n         y_bar_bar=mean(y),\n         Lab=paste0(\"bar(y)[\", Group, \"]\"))\n\n# plot\nggplot(samp_df, aes(y, colour=Group)) + \n  # population in background\n  geom_hline(yintercept=0, linewidth=0.2, colour=\"grey80\") +\n  geom_line(data=pop_df, aes(value, density), linewidth=1, alpha=0.25) + \n  geom_text(data=mu_df, \n            aes(x=mu, y=-density*0.05, label=Lab), \n            vjust=1, parse=T, size=6, alpha=0.5) +\n  geom_segment(data=mu_df, \n               aes(x=mu, xend=mu, y=-density*0.05, yend=0), \n               linewidth=2, linetype=1, alpha=0.5) +\n  # observations\n  geom_point(aes(y, ypos), size=2.5, shape=1, stroke=1) +\n  # group means\n  geom_segment(aes(x=y_bar, xend=y_bar, yend=0, y=y_bar_lab), linewidth=0.75, linetype=2) +\n  geom_text(aes(x=y_bar, y=y_bar_lab, label=Lab), nudge_y=0.02, parse=T, size=6) +\n  # grand mean\n  geom_segment(aes(x=y_bar_bar, xend=y_bar_bar, yend=0, y=y_bar_lab), colour=\"black\",\n               linewidth=0.75, linetype=2) +\n  annotate(\"text\", x=samp_df$y_bar_bar[1], y=samp_df$y_bar_lab[1]+0.02, label=\"bar(bar(y))\", \n           parse=T, size=6, colour=\"black\") +\n  # within-group variation\n  geom_segment(aes(x=y_bar, xend=y, y=ypos, yend=ypos), \n               arrow=arrow(ends=\"both\", length=unit(0.05, \"inches\")), colour=\"black\") +\n  # among-group variation\n  geom_segment(aes(x=y_bar, xend=y_bar_bar, y=y_bar_lab*0.9, yend=y_bar_lab*0.9), \n               arrow=arrow(ends=\"both\", length=unit(0.1, \"inches\")), \n               colour=\"black\", linewidth=1) +\n  scale_colour_manual(values=c(\"steelblue2\", \"firebrick\"), guide=\"none\") +\n  x_lim + y_lim + \n  labs(x=\"Response variable\", y=\"\")\n```\n\n::: {.cell-output-display}\n![Sources of variation (within group vs. among groups) as quantified by ANOVA. Points are observations, dashed vertical lines give sample means for A (blue), B (red), and overall (black). Thick arrows show differences between group means and the overall mean, and thin arrows show differences between observations and group means. The population means (mu[A], mu[B]) and the effect size (mu[B] - mu[A]) are unknown and must be inferred from the sample with confidence intervals.](P5_ANOVA_regression_files/figure-html/fig-ANOVA_overview-1.png){#fig-ANOVA_overview width=672}\n:::\n:::\n\n\nThe null hypothesis in an ANOVA is that there is no difference in group means: $\\mu_A = \\mu_B = ... = \\mu_k$. Under the null hypothesis, the data come from a single population and our groupings are meaningless with regard to the response variable. \n\nIn some cases, this may be of interest. What is almost always more interesting, however, is estimating means, differences between means, and our confidence in those.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse); theme_set(theme_classic())\nlibrary(readxl)\nlibrary(emmeans)\nset.seed(2026)\n```\n:::\n\n\n### ANOVA in R\n\nThere are numerous variations on the theme of ANOVA. We cover one-way ANOVA and we mention two-way ANOVA. The objective of ANOVA is to establish the size of the difference (called the ‘effect size’) between different groups (e.g., treatments or locations) and put a confidence interval on those differences.\n\n### One-way ANOVA\n\nOne-way ANOVA is a procedure we use to estimate the magnitude of differences between means of two or more groups. We also use it to put confidence intervals on those differences.\n\nThe first example data is the yield in $\\mu g ~ C ~ ml^{-1}$ of a species of microalgae (*Isochrysis galbana*) in laboratory culture exposed to three light levels (low, medium, high). We are interested in these particular light levels because they represent the means of winter, spring, and summer Scottish sun intensity. The data are in the worksheet ‘Microalgae’.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalgae_wide_df <- read_excel(\"data/H2SMS_practicalData.xlsx\", sheet = \"Microalgae\")\n```\n:::\n\n\nCheck these data as usual.\n\n::: Q.\nWhat is your objective in this type of experiment? What are you interested in estimating?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nWe want to estimate the population means, differences between pairs of means, and our confidence in each of those estimates.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nWhat assumptions should be met prior to undertaking parametric ANOVA?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nThe residual error should be approximately normally distributed, the variance within each group should be approximately equal, and observations within each group should be independent.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nUnder which circumstances could you begin to relax the assumption that the data are normally distributed (think central limit theorem)?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nWith large enough sample sizes (at least 30 or so) this assumption becomes less important since the sample means are likely to be normally distributed regardless of the data distribution.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nWhat is the sample size in this case? Can we assume sample means will be normally distributed?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(algae_wide_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\nNo, under the CLT, with n = 5, we cannot assume sample means will be normally distributed unless the data are normally distributed.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nAre the data normally distributed? Be careful how you word your answer to this question.\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nNo, it's a bit pedantic, but data are never 'truly' normally distributed.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nIs it reasonable to assume that these data are drawn from a population that is normally distributed?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nWith this small of a sample size, it's very difficult to assess. So we'll go ahead and assume that it's reasonable.\n\n:::\n\n:::\n\n:::\n\nTo work with our data, we need to rearrange the `data.frame` to a tidy format with each variable corresponding to one column, and each observation corresponding to one row. We'll use the *tidyverse* as before.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(algae_wide_df, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n    low medium  high\n  <dbl>  <dbl> <dbl>\n1  13.1   12    14.2\n2  11.5   11.5  13.1\n```\n\n\n:::\n\n```{.r .cell-code}\nalgae_df <- algae_wide_df |>\n  pivot_longer(everything(), names_to = \"Treatment\", values_to = \"Yield\")\nglimpse(algae_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 15\nColumns: 2\n$ Treatment <chr> \"low\", \"medium\", \"high\", \"low\", \"medium\", \"high\", \"low\", \"me…\n$ Yield     <dbl> 13.07599, 12.00000, 14.20000, 11.53923, 11.50000, 13.10000, …\n```\n\n\n:::\n:::\n\n\n::: Q.\nWhat do you notice about the variable types? Prepare `algae_df$Treatment` for analysis and plotting.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## View solution\n\nThe column should be a `factor` with the levels in a logical order. Remember that unless you specify the levels, R will order them alphabetically. In this case, that would be `\"high\", \"low\", \"medium\"`.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nalgae_df$Treatment <- factor(algae_df$Treatment, \n                             levels=c(\"low\", \"medium\", \"high\"))\nglimpse(algae_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 15\nColumns: 2\n$ Treatment <fct> low, medium, high, low, medium, high, low, medium, high, low…\n$ Yield     <dbl> 13.07599, 12.00000, 14.20000, 11.53923, 11.50000, 13.10000, …\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(algae_df, aes(Treatment, Yield)) + \n  geom_boxplot() +\n  geom_point(shape=1)\n```\n\n::: {.cell-output-display}\n![Boxplot of algal yield at different light levels.](P5_ANOVA_regression_files/figure-html/fig-algae_boxplot-1.png){#fig-algae_boxplot width=528}\n:::\n:::\n\n:::\n\nWhile there are formal tests to evaluate model assumptions (e.g., the Shapiro-Wilkes test or the Bartlett test), a better way of checking model assumptions is to investigate the residual error. **Residual error** is the difference between the actual data values and the values predicted by the model. Here we have randomly assigned five cultures each of the same species to three specific treatments (light levels).\n\n::: callout-note\n**Residual error** is the leftover noise: the difference between your model prediction and each observation.\n\n**Sampling error** is the error due to the sampling process: the difference between your model prediction and the true population value.\n:::\n\nNext to conduct the analysis. This is a one-way ANOVA (one predictor) with fixed effects (we are interested in the differences between specific groups rather than characterizing the variation among groups generally).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalgae_aov <- aov(Yield ~ Treatment, data = algae_df) # ?aov\n```\n:::\n\n\n\n::: callout-note\nThe function to conduct an ANOVA is `aov()`. The function `anova()` converts various statistical model outputs to the standard ANOVA-table output, including any from the GLM family. An ANOVA table can be produced with `aov(...)` or `anova(lm(...))`, but post-hoc analysis requires `aov()`.\n:::\n\nBefore we look at the output, let's assess the assumptions using the residuals. Rather than using `qqnorm()` as in @sec-P3, it is better to use `plot(aov_object)`. These default residual plots (@fig-algae_aov) enable us to rapidly assess whether the model assumptions are reasonable. Remember, the assumptions to assess here are:\n\n1. The *residual error* is normally distributed (rather than variable per se, which is what `qqnorm()` gives).\n2. The *residual error* is homoscedastic, with constant variance across groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2), mar=c(4,4,1,1)) \nplot(algae_aov) \n```\n\n::: {.cell-output-display}\n![Residual plots from one-way ANOVA.](P5_ANOVA_regression_files/figure-html/fig-algae_aov-1.png){#fig-algae_aov width=528}\n:::\n:::\n\n\n**Interpretation of residual patterns:**\n\n-   **Upper left:** Residuals v. fitted. This is the residual values against the fitted values. The fitted values are the means of the three groups (remember that ANOVA is about comparing means). The spread for the lower values (low and medium light) is higher than for the high light so this might make us consider the homoscedasticity assumption.\\\n-   **Upper right:** Normal Q-Q plot. This assesses the normality assumption. The points (each point is an observation) lie around the straight line so this assumption is reasonable. Note that general linear models assume that the means of groups are normally distributed, and this always applies when the means are based on large sample sizes (roughly $n > 30$). When $n < 30$, you should check that the distribution of the residuals is reasonably ‘normal’.\\\n-   **Lower left:** Scale-location. This specifically looks to assess whether residual magnitude increases with fitted values, which is a common issue in these types of analyses. In this case, the scale decreases with fitted value. This is similar to the Upper Left plot, but with `sqrt(abs(standardized_residuals))` on the y-axis instead of just `residuals` to focus just on the magnitude of the residuals.\\\n-   **Lower right:** Constant leverage, residuals vs. factor levels. This indicates how each treatment is fitted (i.e. the residuals associated with each treatment). You might be concerned if one particular treatment was associated with extremely high residuals (outliers). R automatically identifies potential outliers (8, 11, and 13 in this case) for you to further assess. In this case there is nothing in particular to worry about.\n\nThe residual plots allow you to investigate different aspects of the data and the how their assumptions are met. The interpretation of the plots overlaps in the sense that the same issue might be apparent in several of the plots.\n\n::: Q.\nWhat are the ‘fitted values’ for an ANOVA?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nThe fitted values are the sample means. They are the best prediction for any new data we might collect.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nAre your effects fixed or random?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nFixed. We are concerned with specific predictor levels and the labels are meaningful.\n\n:::\n\n:::\n\n:::\n\nEverything looks OK, so we can then look at the results of the ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# anova(algae_aov) # outputs an anova-type table, but unnecessary with aov()\nsummary(algae_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \nTreatment    2 10.050   5.025   6.487 0.0123 *\nResiduals   12  9.296   0.775                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: Q.\nAssuming you have chosen $\\alpha = 0.05$, what do you conclude? What might you be interested in going on to test next? \n:::\n\nReporting that there are ‘significant’ differences between means is not enough. What your readers should be interested in is what the differences between the means actually are, and how confident you are in your assessment. This can be provided by the Tukey HSD test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# HSD stands for 'honestly significant difference'\nalgae_grp_diffs <- TukeyHSD(x = algae_aov, conf.level = 0.95) \nalgae_grp_diffs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = Yield ~ Treatment, data = algae_df)\n\n$Treatment\n                   diff        lwr      upr     p adj\nmedium-low  -0.09077539 -1.5758551 1.394304 0.9854641\nhigh-low     1.68922461  0.2041449 3.174304 0.0260570\nhigh-medium  1.78000000  0.2949203 3.265080 0.0194474\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(algae_grp_diffs)\n```\n\n::: {.cell-output-display}\n![Tukey HSD plot from a one-way ANOVA.](P5_ANOVA_regression_files/figure-html/fig-algae_aov_Tukey-1.png){#fig-algae_aov_Tukey width=768}\n:::\n:::\n\n\nThe mean yield under high light is significantly higher than under both low light (mean difference [95% CI]: 1.69 [0.204-3.17] $\\mu g ~ C ~ml^{-1}$; p=0.03) and medium light (1.78 [0.295-3.27] $\\mu g ~ C ~ml^{-1}$, p=0.02). There was no significant difference between low and medium light levels (p=0.99). \n\n::: Q.\nIn the output from `TukeyHSD()`, why is the first value in `diff` negative?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nAs stated in the first column, the values are for `medium-low`. So if the mean for `low` is larger than the mean for `medium`, this will be negative.\n\n:::\n\n:::\n\n:::\n\nWe of course also want to report the group means with confidence intervals. While we could calculate these individually as in @sec-P4, the simplest way is to use the *emmeans* package. This has the added benefit of using our model's assumption of homoscedasticity in calculating the standard error.\n\nThe `emmeans()` function can correctly calculate means and confidence intervals for complex models (`?emmeans`). Our model is simple, so we only need to provide our `aov` object and the name of the predictor variable (`specs=...`). The confidence level is specified with `level=...`, which is set to `0.95` by default.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalgae_emm <- emmeans(algae_aov, specs=\"Treatment\", level=0.89)\nalgae_emm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Treatment emmean    SE df lower.CL upper.CL\n low         12.1 0.394 12     11.4     12.8\n medium      12.0 0.394 12     11.3     12.7\n high        13.8 0.394 12     13.1     14.5\n\nConfidence level used: 0.89 \n```\n\n\n:::\n\n```{.r .cell-code}\nalgae_emm_df <- as_tibble(algae_emm)\n```\n:::\n\n\nFinally, we should make a figure to communicate the results of our analysis. See the ANOVA lecture and accompanying R script for additional options.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(algae_df, aes(Treatment)) + \n  geom_point(aes(y=Yield), alpha=0.5) +\n  geom_errorbar(data=algae_emm_df, aes(ymin=lower.CL, ymax=upper.CL), colour=\"red\", width=0.1) +\n  geom_point(data=algae_emm_df, aes(y=emmean), shape=1, size=3, colour=\"red\")\n```\n\n::: {.cell-output-display}\n![Algae yield under three light levels. Red points and bars give means and 89% CIs. Black points show observations.](P5_ANOVA_regression_files/figure-html/fig-algae_aov_results-1.png){#fig-algae_aov_results width=384}\n:::\n:::\n\n\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n## Regression\n\nCorrelation and regression are used to examine the strength of association between two variables. In correlation, both variables are measured (and therefore associated with measurement error). In regression, one variable is fixed (by the experimenter) and is assumed to have no ‘error’ associated with it and the other, called the ‘response variable’, is measured (so has measurement error). You must be able to distinguish whether correlation or regression analyses are most appropriate for a given research question and design.\n\nCorrelation analysis is used to measure association, where you are not attempting to formally link cause-and-effect. Regression analysis is generally used where you have experimentally manipulated the fixed factor and are looking at the response in another factor. Causation is implicit in inferential regression analysis (correlation analysis is often used in ‘exploratory’ data analysis where any link between cause-and-effect is inherently more speculative).\n\nThe media often misreport science because it is difficult to resist the impulse to attribute causation. An overwhelming number of spurious correlations (i.e., those *clearly* having no causal relationship) are documented on [tylervigen.com](https://tylervigen.com/spurious-correlations).\n\n### Overview\n\nRegression is at the heart of linear models. ANOVA and t-tests are, basically, special cases of linear regression models. The regression coefficient is a measure of the strength of the relationship between the dependent variable (the one you measure) and the independent variable (the one you fix like a fixed factor in ANOVA). The regression coefficient is denoted by *R^2^* compared with *r* in correlation. The regression coefficient *R^2^* ranges from 0 to 1 (unlike *r* which ranges from -1 to 1). A value $R^2 = 0$ indicates no relationship to the independent variable while $R^2=1$ indicates that the independent variable is entirely responsible for the variability in the measured variable.\n\nAs usual, null hypothesis significance testing is often applied to regression statistics. As usual, the null hypothesis being tested is usually “there is no functional relationship between the response and the predictor” and this is usually conceptually nonsense. In conducting regression analysis, your objective is to quantify to the most appropriate precision and accuracy possible the relationship between X (the aspect you control, the predictor, plotted on the X axis) and Y (the variable you measure, the response, plotted on the Y axis). Your objective is to quantify this relationship, put confidence intervals on it, and then interpret your findings in relation to the objectives of the study and in relation to other research.\n\n::: Q.\nWhat does the plot look like when there is no relationship between the predictor and the response?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nJust a scatter of points. Any line drawn would be flat.\n\n:::\n\n:::\n\n:::\n\nLet us now consider an example in which cause and effect does exist. The data in worksheet ‘Beetles’ in *H2SMS_practicalData.xlsx* shows the weight loss in *Tribolium confusum*, the confused flour beetle, at different relative humidities (data from Sokal and Rohlf, 1995). The relative humidity (RH) to which the beetles are exposed can be fixed and the weight loss (via evaporative losses) of the beetles then assessed. There is no way that the null hypothesis can be true in this case: humidity will obviously influence weight loss in beetles.\n\n::: Q.\nIn this case, what is your response variable (what are you measuring) and your predictor (i.e. what is it that you are manipulating to determine the extent of the response)?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nThe response variable is \"weight loss\" and the predictor is \"relative humidity\".\n\n:::\n\n:::\n\n:::\n\n::: Q.\nPlot the data in R and check your prediction. In this case, the predictor must be displayed on the x-axis and the response must be on the y-axis.\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nSee code below.\n\n:::\n\n:::\n\n:::\n\nWe are interested in whether the whole data set can be usefully represented by a linear regression relationship. We wish to estimate the relationship, and put a confidence interval on our estimate. Common sense tells us that there *is* some sort of relationship (testing a null hypothesis is not very useful) but it might go in either direction (positive or negative) and we don’t know the strength (i.e. slope) of that relationship.\n\n### Linear regression in R\n\nIn R we can use a variety of techniques to conduct linear regression. The easiest is to use `lm()`. It is worth noting that `lm()` would also work for all your other general linear models (e.g. ANOVA). They are, in fact, the same model, it is just the default output (and necessary input formatting) that differs. Try reproducing the ANOVAs above with `anova(lm(...))`.\n\nImport data and begin:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeetle_df <- read_excel(\"data/H2SMS_practicalData.xlsx\", sheet = \"Beetles\")\n# inspect the dataframe, then make a scatter plot\npar(mfrow=c(1,1))\nplot(WeightLoss_Mg ~ Humidity, data = beetle_df) \n```\n\n::: {.cell-output-display}\n![Beetle weight loss as a function of relative humidity.](P5_ANOVA_regression_files/figure-html/fig-beetle_scatter-1.png){#fig-beetle_scatter width=384}\n:::\n:::\n\n\n::: callout-note\nRemember that you can provide `plot()` with either a vector for the x-axis and a vector for the y-axis (i.e., `plot(x_var, y_var)`) *or* you can use a formula, specifying the dataframe (i.e., `plot(y ~ x, data=data_df)`). Just be mindful of which variable is on which axis.\n:::\n\nNow we have explored and plotted the data we can conduct the regression analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# weight loss is modelled as (~) a function of humidity\nbeetle_lm <- lm(WeightLoss_Mg ~ Humidity, data = beetle_df) \n# beetle_lm\n# str(beetle_lm) # lm outputs are complex structures\n```\n:::\n\n\nBefore we go on and interpret the model output we need to assess the model assumptions. This is done in the same way as for ANOVA with the same commands.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2), mar=c(4,4,1,1)) # set up 4 in 1 plot.\nplot(beetle_lm) # plot the regression residuals.\n```\n\n::: {.cell-output-display}\n![Regression diagnostics](P5_ANOVA_regression_files/figure-html/fig-beetle_diag-1.png){#fig-beetle_diag width=480}\n:::\n:::\n\n\nThe small sample size here ($n=9$) makes a proper analysis of the residuals difficult. The plot should be assessed in the same way as for the ANOVA residuals. Basically, any pattern is bad. The upper left (Residuals v Fitted) doesn’t cause any major concern, though the upper right (Normal QQ) indicates a possible problem. Scale-Location (lower left) is difficult to interpret but no obvious pattern is present. The Residuals v. leverage (lower right) indicates a potential issue as well. A point with a large residual (i.e. where it is very different to that expected by the model) and with a high leverage (i.e. at the extreme ends of the predictors range) has a large Cook’s distance and has a disproportionate effect on the slope and intercept. These points should be examined in more detail.\n\n::: Q.\nWhich point has the largest Cook’s distance?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nPoint 1 has the largest Cook's distance.\n\n:::\n\n:::\n\n:::\n\nWe will now proceed to looking at the linear regression analysis results on the basis that the residuals do not raise any concerns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(beetle_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = WeightLoss_Mg ~ Humidity, data = beetle_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.46397 -0.03437  0.01675  0.07464  0.45236 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  8.704027   0.191565   45.44 6.54e-10 ***\nHumidity    -0.053222   0.003256  -16.35 7.82e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2967 on 7 degrees of freedom\nMultiple R-squared:  0.9745,\tAdjusted R-squared:  0.9708 \nF-statistic: 267.2 on 1 and 7 DF,  p-value: 7.816e-07\n```\n\n\n:::\n:::\n\n\nThe regression equation of the form $y = a + bx$ can be determined. The regression equation is:\n\n$WeightLoss = 8.70 - 0.05322 * humidity$\n\nCommon-sense check: the coefficient is negative. As the humidity increases, the weight loss decreases (as expected and shown in the scatter plot).\n\n::: Q.\nWhat is the effect on weight loss of increasing the relative humidity by 10%?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nAn increase of relative humidity of 10% would decrease the weight loss by 0.5322 mg.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nWhat is the weight loss, predicted by the model, when relative humidity is 0%?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n8.70 mg\n\n:::\n\n:::\n\n:::\n\n::: Q.\nWhat does the model suggest the weight loss will be when relative humidity is -50% and +150%? Are these values sensible? What does this tell you about extrapolating beyond the data range in using regression analysis in predictions?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n::: {.cell}\n\n```{.r .cell-code}\n8.70 - 0.05322 * -50\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11.361\n```\n\n\n:::\n\n```{.r .cell-code}\n8.70 - 0.05322 * 150\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.717\n```\n\n\n:::\n:::\n\n\nIt is the responsibility of the researcher to determine what is reasonable. The statistics and equations are completely ignorant about the data. Rubbish in, rubbish out.\n\n:::\n\n:::\n\n:::\n\nThe residual error is the variance in y around the line. The *R^2^* is the proportion of this variance that is explained by the regression line. In the current case $R^2 = 0.97$. This is an extremely high value and indicates that the regression model is extraordinarily good at accounting for the variance in weight loss based on the relative humidity.\n\nThe P values allow us to assess if the slope and the intercept are likely different from zero.\n\n::: Q.\nGiven the very high *R^2^* (and looking at your plot) would you expect the regression model to be significantly better than the null model in explaining the variance in weight loss?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nYes.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nWith $\\alpha = 0.05$, do you reject or accept the null hypothesis? What would you wish to report in relation to the slope coefficient if you were reporting the results from this analysis?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nReject the null hypothesis. We would report the values and their confidence intervals.\n\n:::\n\n:::\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(beetle_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %      97.5 %\n(Intercept)  8.25104923  9.15700538\nHumidity    -0.06092143 -0.04552287\n```\n\n\n:::\n:::\n\n\nThe confidence intervals are, again, ‘clunky’ to describe.\n\nIf we imagine there were many alternate you's (like in a multiverse) repeating the same experiment on the same population with the same sample size (but independent *samples*), and each 'you' calculated 95% CIs with `confint()`, then 95% of you would have intervals that include the true population intercept and slope. While you do not know if you are in the unlucky 5% that failed to capture the population values, the 95% confidence interval serves as our best estimate for likely values (but see Bayesian statistics for more intuitive intervals!).\n\n### Plotting the regression line and confidence intervals\n\nA regression model (i.e. the linear relationship between the predictor and response variables) allows us to predict values for any value of the predictor, along with confidence levels. We can plot this regression line without too much effort.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeetle_pred_line <- predict(beetle_lm, interval = \"confidence\", level = 0.95)\n\npar(mfrow=c(1,1))\nplot(WeightLoss_Mg ~ Humidity, data = beetle_df, ylim=c(3, 10),\n     xlab = \"Relative humidity (%)\", ylab = \"Weight loss (mg)\") \nlines(beetle_df$Humidity, beetle_pred_line[, \"fit\"])\nlines(beetle_df$Humidity, beetle_pred_line[, \"lwr\"], lty = 2)\nlines(beetle_df$Humidity, beetle_pred_line[, \"upr\"], lty = 2)\n```\n\n::: {.cell-output-display}\n![Regression line (solid) with upper and lower 95\\% confidence intervals on the regression line (dashed).](P5_ANOVA_regression_files/figure-html/fig-beetle_regline-1.png){#fig-beetle_regline width=384}\n:::\n:::\n\n\nTry generating 90% confidence intervals and add them to the plot.\n\n::: Q.\nWhich will have the wider interval, a 99.99% interval or a 50% interval and why?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nThe 99.99% interval will be wider. For a 50% interval, only 50% of samples would capture the true line, so 50% would exclude it. The 99.99% intervals need to be wide enough that 99.99% of samples include the true line and only 0.01% exclude it.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nDo the confidence intervals in @fig-beetle_regline run parallel to the regression line?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nNo, they are narrowest in the centre and wider at either end.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nIf not, what does this suggest about the degree of confidence you have in values predicted at various points along the line?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nWe are more confident about the values near the centre.\n\n:::\n\n:::\n\n:::\n\n::: Q.\nAt what value of relative humidity are your predictions of weight loss likely most accurate?\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\nThe mean, which is about 50% humidity.\n\n:::\n\n:::\n\n:::\n\nWe can make predictions based on our regression line, and put confidence intervals on those predictions. Say we had a relative humidity of 50% in the above example. You could ask for the model-predicted weight loss and you’d want confidence intervals on that prediction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# predict() needs a data.frame with the same predictors used in beetle_lm\npredict(beetle_lm, \n        newdata = data.frame(Humidity = 50), \n        interval = \"predict\", \n        level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      fit      lwr      upr\n1 6.04292 5.303471 6.782368\n```\n\n\n:::\n\n```{.r .cell-code}\n# or more fully:\npredict(beetle_lm, \n        newdata = data.frame(Humidity = seq(0, 100, by=25)), \n        interval = \"predict\", \n        level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 8.704027 7.868990 9.539064\n2 7.373474 6.608630 8.138317\n3 6.042920 5.303471 6.782368\n4 4.712366 3.949031 5.475701\n5 3.381812 2.549540 4.214084\n```\n\n\n:::\n:::\n\n\nAnd we can plot these intervals too:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_humidity_df <- data.frame(Humidity = 0:100)\nbeetle_pred_line <- predict(beetle_lm, \n                            newdata = new_humidity_df,\n                            interval = \"confidence\", \n                            level = 0.95)\nbeetle_pred_obs <- predict(beetle_lm,\n                           newdata = new_humidity_df, \n                           interval = \"prediction\", \n                           level = 0.95)\n\npar(mfrow=c(1,1))\nplot(WeightLoss_Mg ~ Humidity, data = beetle_df, ylim=c(3, 10),\n     xlab = \"Relative humidity (%)\", ylab = \"Weight loss (mg)\") \nlines(new_humidity_df$Humidity, beetle_pred_line[, \"fit\"])\nlines(new_humidity_df$Humidity, beetle_pred_line[, \"lwr\"], lty = 2)\nlines(new_humidity_df$Humidity, beetle_pred_line[, \"upr\"], lty = 2)\nlines(new_humidity_df$Humidity, beetle_pred_obs[, \"lwr\"], lty = 3)\nlines(new_humidity_df$Humidity, beetle_pred_obs[, \"upr\"], lty = 3)\n```\n\n::: {.cell-output-display}\n![Regression line (solid) with upper and lower 95\\% confidence intervals on the regression line (dashed) and 95% prediction intervals (dotted).](P5_ANOVA_regression_files/figure-html/fig-beetle_regline_predInterval-1.png){#fig-beetle_regline_predInterval width=384}\n:::\n:::\n\n\nThese are prediction intervals and they are broader than confidence intervals. The confidence intervals express your confidence about the *regression line* for the population. The prediction interval expresses your confidence about the distribution of the *observations* for the population. \n\n------------------------------------------------------------------------\n\n## Further practice\n\n\n\n### Scenario 1\n\n**Question:** What is the relationship between phosphate concentration and absorbance?\n\nImport the 'PhosphateCalibration' sheet from \"H2SMS_practicalData.xlsx\" (1st year practical data) into R and perform an appropriate analysis with absorbance predicted by concentration. Perform all appropriate checks for data quality and assumptions. Report relevant results with 92% confidence intervals.\n\n::: {.callout-tip collapse=\"true\"}\n## View solution\n\n::: {.callout-tip collapse=\"true\"}\n## View analysis type\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Response variable and type\"}\n# 'Absorbance' is continuous\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Predictor variable and type\"}\n# 'Concentration' is continuous\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Analysis type\"}\n# Linear regression: The predictor and response are both continuous\n```\n:::\n\n\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## View step 1\n\nFirst load and prepare the data.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nphosphate_df <- read_xlsx(\"data/H2SMS_practicalData.xlsx\", \"PhosphateCalibration\")\nphosphate_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  Concentration Absorbance\n          <dbl>      <dbl>\n1           0        0.001\n2           0.2      0.006\n3           0.5      0.011\n4           1        0.031\n5           2        0.054\n6           3        0.067\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nplot(Absorbance ~ Concentration, data = phosphate_df)\n```\n\n::: {.cell-output-display}\n![Phosphate calibration data.](P5_ANOVA_regression_files/figure-html/fig-phosphatePoints-1.png){#fig-phosphatePoints width=480}\n:::\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## View step 2\n\nSecond, run the linear regression.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nphos.mod <- lm(Absorbance ~ Concentration, data = phosphate_df)\n```\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## View step 3\n\nThird, check assumptions.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow=c(2,2), mar=c(4,4,1,1))\nplot(phos.mod)\n```\n\n::: {.cell-output-display}\n![Phosphate calibration regression diagnostics.](P5_ANOVA_regression_files/figure-html/fig-phosphateDiagnostics-1.png){#fig-phosphateDiagnostics width=480}\n:::\n:::\n\n\nIf the assumptions seem invalid, try transformations. Once satisfactory, continue.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## View step 4\n\nFourth, view the results and evaluate the null hypothesis.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(phos.mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Absorbance ~ Concentration, data = phosphate_df)\n\nResiduals:\n        1         2         3         4         5         6 \n-0.001605 -0.001213 -0.003125  0.005355  0.005314 -0.004726 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   0.002605   0.002853   0.913 0.412856    \nConcentration 0.023040   0.001849  12.464 0.000238 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.004823 on 4 degrees of freedom\nMultiple R-squared:  0.9749,\tAdjusted R-squared:  0.9686 \nF-statistic: 155.3 on 1 and 4 DF,  p-value: 0.0002383\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## View step 5\n\nFifth, produce a figure with the best fit line and 92% confidence intervals.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nnewPhosphate <- tibble(Concentration=seq(min(phosphate_df$Concentration),\n                                         max(phosphate_df$Concentration),\n                                         length.out=100))\nphos_pred_line <- predict(phos.mod, \n                          newdata = newPhosphate,\n                          interval = \"confidence\", \n                          level = 0.92)\n\nplot(Absorbance ~ Concentration, data = phosphate_df)\nlines(newPhosphate$Concentration, phos_pred_line[, \"fit\"])\nlines(newPhosphate$Concentration, phos_pred_line[, \"lwr\"], lty = 2)\nlines(newPhosphate$Concentration, phos_pred_line[, \"upr\"], lty = 2)\n```\n\n::: {.cell-output-display}\n![Phosphate calibration scatter plot with best fit line and 92% confidence intervals.](P5_ANOVA_regression_files/figure-html/fig-phosphateScatter-1.png){#fig-phosphateScatter width=384}\n:::\n:::\n\n\nReport the results. In a full report or paper, this should include the intercept and slope with CIs, p-value, R^2^, and likely a figure communicating the results.\n:::\n\n:::\n\n\n::: callout-note\nMost often, researchers report 95% CIs, but occasionally 80%, 90%, or 95%. It would be a bit cheeky to report the 92% CIs, but keep in mind that there is nothing magic about 95% (just like 0.05). \n:::\n\n::: Q.\nFor a concentration of 0.75 units, what values would you expect (95 times in 100) to see from your experimental set-up?\n\nYou should get:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n         fit         lwr        upr\n1 0.01988519 0.005298129 0.03447225\n```\n\n\n:::\n:::\n\n\n::: {.content-hidden when-profile=\"man\"}\n\n::: callout-important\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(phos.mod, newdata=data.frame(Concentration = 0.75), interval = \"predict\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         fit         lwr        upr\n1 0.01988519 0.005298129 0.03447225\n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n\n:::\n\n\n### Scenario 2\n\n**Question:** How does limpet travel distance (within a set timespan) vary by surface type?\n\nImport the 'LimpetDist' sheet from \"H2SMS_practicalData.xlsx\", which gives travel distance of limpets on three different surface types. Perform an appropriate analysis of distance predicted by surface type. Make sure you perform appropriate data quality checks and assumption checks. Report results as appropriate.\n\n::: {.callout-tip collapse=\"true\"}\n## View solution\n\n::: {.callout-tip collapse=\"true\"}\n## View analysis type\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Response variable and type\"}\n# 'Travel distance' is continuous\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Predictor variable and type\"}\n# 'Surface type' is categorical\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Analysis type\"}\n# ANOVA: The predictor is categorical and the response is continuous\n```\n:::\n\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## View step 1\n\nFirst load and prepare the data.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nlimpet_wide_df <- read_excel(\"data/H2SMS_practicalData.xlsx\", sheet = \"LimpetDist\")\nlimpet_df <- limpet_wide_df |>\n  pivot_longer(everything(), names_to=\"Surface\", values_to=\"Distance\") |>\n  mutate(Surface=factor(Surface, levels=c(\"Smooth\", \"Intermediate\", \"Rough\")))\nglimpse(limpet_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 24\nColumns: 2\n$ Surface  <fct> Smooth, Intermediate, Rough, Smooth, Intermediate, Rough, Smo…\n$ Distance <dbl> 97, 66, 55, 83, 98, 49, 90, 78, 41, 93, 70, 64, 71, 89, 69, 1…\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nggplot(limpet_df, aes(Surface, Distance)) + \n  geom_boxplot() +\n  geom_point(shape=1)\n```\n\n::: {.cell-output-display}\n![Boxplot of limpet travel distances by surface.](P5_ANOVA_regression_files/figure-html/fig-limpetBoxplot-1.png){#fig-limpetBoxplot width=768}\n:::\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## View step 2\n\nSecond, run the ANOVA.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nlimpet_aov <- aov(Distance ~ Surface, data=limpet_df)\n```\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## View step 3\n\nThird, check assumptions.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\npar(mfrow = c(2, 2), mar=c(4,4,1,1)) \nplot(limpet_aov) \n```\n\n::: {.cell-output-display}\n![Residual plots from the limpet one-way ANOVA.](P5_ANOVA_regression_files/figure-html/fig-limpet_aov-1.png){#fig-limpet_aov width=528}\n:::\n:::\n\n\nIf the assumptions seem invalid, try transformations. Once satisfactory, continue.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## View step 4\nIn this case, the residuals show that the assumptions of normally distributed residuals with homoscedasticity among groups are reasonable. No transformation is needed.\n\nFourth, produce the ANOVA table and evaluate the null hypothesis.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nsummary(limpet_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nSurface      2   4478  2239.1   18.99 1.95e-05 ***\nResiduals   21   2476   117.9                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nIf you failed to reject $H_0$, report this and stop. Otherwise, continue.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## View step 5\n\nWe've rejected the omnibus null hypothesis, so we proceed with pairwise comparisons to determine which means are different from each other, by how much, and how confident we are in that difference. We also of course calculate means for each group with CIs.\n\nFifth, calculate group means with CIs and perform a Tukey HSD test.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nemmeans(limpet_aov, specs=\"Surface\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Surface      emmean   SE df lower.CL upper.CL\n Smooth         89.8 3.84 21     81.8     97.7\n Intermediate   75.1 3.84 21     67.1     83.1\n Rough          56.4 3.84 21     48.4     64.4\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nlimpet_grp_diffs <- TukeyHSD(x = limpet_aov) \nlimpet_grp_diffs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = Distance ~ Surface, data = limpet_df)\n\n$Surface\n                       diff       lwr         upr     p adj\nIntermediate-Smooth -14.625 -28.31037  -0.9396343 0.0348495\nRough-Smooth        -33.375 -47.06037 -19.6896343 0.0000123\nRough-Intermediate  -18.750 -32.43537  -5.0646343 0.0064480\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View code\"}\nplot(limpet_grp_diffs)\n```\n\n::: {.cell-output-display}\n![Tukey HSD plot from a one-way ANOVA.](P5_ANOVA_regression_files/figure-html/fig-limpet_aov_Tukey-1.png){#fig-limpet_aov_Tukey width=768}\n:::\n:::\n\n\nReport the results. In a full report or paper, this should include the ANOVA table, group means and CIs, effect sizes and CIs, and likely a figure communicating the results.\n:::\n\n:::\n\n\n\n\n------------------------------------------------------------------------\n\n## Conclusions\n\nCorrelation is a measure of association between two variables. It is appropriate to use correlation to measure this association when one cannot or does not wish to assume that any relationship is causative. Pearson correlation coefficients should only be used where it is fair to assume (by looking at scatter plot) that the relationship is approximately linear. Where linearity does not apply, attempt to transform one or both of the variables. Where there are outliers (that cannot be removed) or where one is uncertain about some of the data, then non-parametric ranked based correlation coefficients, such as the Spearman coefficient, should be used. As with GLMs, correlation analysis assumes that all points are independent of each other.\n\nLinear regression is one of the most widely used statistical techniques. It is used to examine causal relationships, often where experimental manipulations are conducted. Regression is a general linear model and it lies within the generalized linear model family (GLMs). GLMs allow you to model data that is not normally distributed, including proportions (bounded by 0 and 1), or counts (bounded by 0). Using a GLM is a much better way of analyzing these data compared with transforming the response variable or using non-parametric techniques. All members of the GLM family make the assumptions that measurements are independent of each other. Where this assumption fails you can use generalized linear mixed models (GLMMs). Extensions of simple linear regression include multiple regression which examines the influence of two or more continuous variables on a response variable.\n",
    "supporting": [
      "P5_ANOVA_regression_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}